### ISSUE TITLE
Please update MaterialEditText to latest.

### ISSUE THREAD

**Issue by FongMi** [Lesilva/BetterSpinner#1]
Please update MaterialEditText to latest, and is anyway to use setSelection like Spinner ?
I try to use setSelection, but show error... 
 java.lang.IndexOutOfBoundsException: setSpan (1 ... 1) ends beyond length 0

**Comment by Lesilva** [comment]
@FongMi I will update it sometime today. For BetterSpinner, you don't have to use `setSelection`, use `setText` since it acts like a EditText Field.

**Comment by FongMi** [comment]
@Lesilva Thanks, I solved it by setText.

**Comment by Lesilva** [comment]
@FongMi No problem. By the way, MaterialEditText 2 is still in snapshot release. I might not add it in right away. I think I need to find a better way to work with MaterialEditText regarding versions etc.
