### ISSUE TITLE
Wrap dropdown content

### ISSUE THREAD

**Issue by packruler** [Lesilva/BetterSpinner#10]
Is there a way to wrap content of drop down menu with a width larger than the size of spinner?

**Comment by Lesilva** [comment]
You can use [android:dropDownWidth](https://developer.android.com/reference/android/widget/AutoCompleteTextView.html#attr_android:dropDownWidth) in xml or [setDropDownWidth](https://developer.android.com/reference/android/widget/AutoCompleteTextView.html#setDropDownWidth(int)) in code to set the width of drop down.
