### ISSUE TITLE
setOnItemSelectedListener does not work

### ISSUE THREAD

**Issue by azizj1** [Lesilva/BetterSpinner#11]
I added a listener to setOnItemSelectedListener, but those methods never get called:

        PaddedStringArrayAdapter deptAdapter = new PaddedStringArrayAdapter(getActivity(),
                android.R.layout.simple_spinner_item, getDepartmentNames());
        deptAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        MaterialBetterSpinner deptSpinner = (MaterialBetterSpinner) view.findViewById(R.id.deptSpinner);
        deptSpinner.setAdapter(deptAdapter);
        deptSpinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                Toast.makeText(parent.getContext(), "onItemSelected", Toast.LENGTH_SHORT).show();
                Log.d("Console", "item selected");
            }

            @Override
            public void onNothingSelected(AdapterView<?> parent) {
                Log.d("Console", "nothing selected");
            }
        });

I also tried the setOnItemClickListener, but then the spinner takes a double tap to open, which is definitely not desirable. 

        deptSpinner.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                //Toast.makeText(parent.getContext(), "onItemSelected", Toast.LENGTH_SHORT).show();
                Log.d("Console", "item selected");
            }
        });

Thank you and I look forward to your reply.

**Comment by Lesilva** [comment]
If you take a look at the [code](https://github.com/Lesilva/BetterSpinner/blob/master/library-material/src/main/java/com/weiwangcn/betterspinner/library/material/MaterialBetterSpinner.java), I'm using OnItemClickListener in my code as well, so if you override it, it will break. The solution to your problem is just copy the java file over to you project and modify it as you want. For now, that's all I can think of.

**Comment by azizj1** [comment]
Yea I ended up making a composite listener so it doesn't get overridden. I'll push my changes soon

**Comment by sekharrockz** [comment]
Thanks.

**Comment by BatshevaR** [comment]
I'm getting this same issue, 
I sew it is unrecommended to use a OnItemClickListener 
why not instead change your source code to use OnItemSelectedListener?
it would be helpful for everybody

**Comment by bantyK** [comment]
In case of multiple spinners in a single layout, how to get the id of the selected spinner in onItemSelectedListener **(parent.getId() always returns -1)**

**Comment by iamkdblue** [comment]
categorySpinner.**setOnItemClickListener**(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                Log.d("kkkk",""+position);
            }
        });
setOnItemClickListener Solved My Problem

**Comment by csangeeta** [comment]
Hello,
I am getting same issue. onItemSelected not calling and it is not displaying on the spinner as text, 
Find my code below. 

 ArrayAdapter<String> dataAdapter = new ArrayAdapter<String>(this, android.R.layout.simple_spinner_item, products);
        dataAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        products_mod.setAdapter(dataAdapter);
        products_mod.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> adapterView, View view, int i, long l) {
                Log.d("onItemSelected ",""+i);
            }
            @Override
            public void onNothingSelected(AdapterView<?> adapterView) {
            }
        });

**Comment by thumb2thiefapp** [comment]
@csangeeta try this code its may be help you !
products_mod.setOnItemClickListener(new AdapterView.OnItemClickListener() {
@override
public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
Log.d("kkkk",""+position);
}
});

**Comment by gtl23** [comment]
@thumb2thiefapp  setOnItemClickListener cannot be used with spinner, BTW i'm also having the same issue. I've implemented the spinner as stated by the official android documentation. In one of the files of my project it is working as expected but not in the the other files. All the implementations are correctly done as stated by the official documentation in all the files.

**Comment by csangeeta** [comment]
Thank you @thumb2thiefapp and @gtl23.

**Comment by iamkdblue** [comment]
@csangeeta your welcome !

**Comment by JamworksPro** [comment]
If you create a new List Adapter WITH AN EMPTY LIST the setOnItemSelectedListener will never be called.  Add at least one item to the list BEFORE creating the the adapter for it

**Comment by RandyBlythe0** [comment]
> If you create a new List Adapter WITH AN EMPTY LIST the setOnItemSelectedListener will never be called. Add at least one item to the list BEFORE creating the the adapter for it

That solved my issue Thanks

**Comment by TechLee2019** [comment]
This code will help you

ArrayAdapter<String> adapter = new ArrayAdapter<String>(getActivity(), android.R.layout.simple_list_item_1, items);

        m_ListView.setAdapter(adapter);
        m_ListView.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                Log.v("item", (String) parent.getItemAtPosition(position));
                Toast.makeText(getActivity(), (String) parent.getItemAtPosition(position), Toast.LENGTH_LONG).show();
                Toast.makeText(getActivity(), "working", Toast.LENGTH_LONG).show();

                if (position == 1) {
                    Intent intent = new Intent(getContext(), CategoriesActivity.class);
                    startActivity(intent);
                }
//                ((TextView) parent.getChildAt(0)).setTextColor(Color.WHITE);
            }
            @Override
            public void onNothingSelected(AdapterView<?> parent) {
                // TODO Auto-generated method stub
                Log.v("item", (String) parent.getItemAtPosition(0));
            }
        });
