### ISSUE TITLE
Can not use "setselection(int pos)" for the spinner

### ISSUE THREAD

**Issue by sekharrockz** [Lesilva/BetterSpinner#13]

**Comment by Lesilva** [comment]
Just use `setText()`.

**Comment by sekharrockz** [comment]
Hey, i have copied your Library Code of Better Spinner to my code. Now, can i customize the setSelection method.??? 

Thanks.

**Comment by congdanh1608** [comment]
setselection(int pos) is crashed
Use spinner.setText(adapter.getItem(i).toString()) to resolve this issue.

**Comment by luckcoolla** [comment]
I've added To MaterialBetterSpinner class method for the manual position edit:

```java
    public void setPosition(int position) {
        mPosition = position;
    }
```

+ you have to call spinner.setText(value)

**Comment by Madina-S** [comment]
I need to fire the selection, so other UI components change accordingly
