### ISSUE TITLE
android:allowBackup should not be used in library

### ISSUE THREAD

**Issue by grine4ka** [Lesilva/BetterSpinner#19]
Error:Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:47:9
>     is also present at com.weiwangcn.betterspinner:library-material:1.1.0:12:9 value=(true)
>     Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:40:5 to override

**Comment by patheticcockroach** [comment]
+1, as far as I understood, librairies shouldn't set android:allowBackup, as discussed on other repos:
https://github.com/wuman/android-oauth-client/issues/44
https://github.com/grantland/android-autofittextview/pull/30
The fix should be trivial, just remove the line. Made the pull request there for convenience: https://github.com/Lesilva/BetterSpinner/pull/35
