### ISSUE TITLE
No resource identifier found for attribute 'met_floatingLabel'

### ISSUE THREAD

**Issue by xbandx68** [Lesilva/BetterSpinner#23]
I have iserted in my grandle this
compile ('com.weiwangcn.betterspinner:library-material:1.1.0') {
    exclude group: 'com.android.support', module: 'appcompat-v7'
    exclude group: 'com.rengwuxian.materialedittext', module: 'library'
}

and 
in my layout this:

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    tools:context=".MainActivity$HomeFragment"
    android:orientation="vertical"
    android:weightSum="10">
...
...
...
<com.weiwangcn.betterspinner.library.material.MaterialBetterSpinner
                android:id="@+id/spinner2"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:hint="MaterialBetterSpinner"
                app:met_floatingLabel="normal" />

but the compiler report me:

Error:(43) No resource identifier found for attribute 'met_floatingLabel' in package 'com.bandweb.myviewrecipes'

why?

**Comment by Lesilva** [comment]
If you don't have `MaterialEditText ` in your own project, do not exclude it.
