### ISSUE TITLE
How to Reset Spinner and how to select default item after initialization of adapter

### ISSUE THREAD

**Issue by khalid-mahmood** [Lesilva/BetterSpinner#48]
How can i reset Spinner to default ? 
How can i set Default item selected programmatically after initializing adapter?
spinner.setSelection(0); doesn't work

**Comment by douglasjunior** [comment]
Please, check #13 and #38.

What is reset, you mean clean?

**Comment by khalid-mahmood** [comment]
mean empty the spinner with no items.
for that i use spinner.setText("");
spinner.setAdapter(new ArrayAdapter<String>(
            this,
            android.R.layout.simple_dropdown_item_1line,
            new String[]{}));
is there any other best solution ? 
i use spinner.setText(spinner.getAdapter().getItem(0).toString()); for  pre select;

**Comment by douglasjunior** [comment]
To clear the Spinner just clear the adapter.

Save a reference for yout adapater:

```java
ArrayAdapter adapter;

public void onCreate(...) {
      ...
      String[] items = ....;
      adapter = new ArrayAdapter(this, android.R.layout.simple_dropdown_item_1line, items);
      spinner.setAdapter(adapter);
}
```

Then, when you want to clear:

```java
adapter.clear(); // clear items
adapter.notifyDataSetChanged(); // update spinner view
```

**Comment by khalid-mahmood** [comment]
Thank for help ;)

**Comment by Vandana0** [comment]
> mean empty the spinner with no items.
> for that i use spinner.setText("");
> spinner.setAdapter(new ArrayAdapter(
> this,
> android.R.layout.simple_dropdown_item_1line,
> new String[]{}));
> is there any other best solution ?
> i use spinner.setText(spinner.getAdapter().getItem(0).toString()); for pre select;

spinner.setText()?????? Where is that attribute?

**Comment by Madhuprakash1972** [comment]
Hey say one thing why you use adapter ????
